services:

  webapp:
    image: "online-reservation"
    ports:
      - "8080:8080"
    container_name: "webapp"
    networks:
      net:
        ipv4_address: 172.55.55.2


  db:
    image: mysql:8.4.3
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    container_name: "database"
    networks:
      net:
        ipv4_address: 172.55.55.3


networks:
  net:
    name: net
    driver: bridge
    ipam:
      config:
        gateway: 172.55.55.1
        subnet: 172.55.55.0/24